### ISSUE TITLE
Iteration Plan for March 2017

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#837]
- [x] 🏃 Enable running traces and using log file for the Go language server
- [x] 🏃 #299 Run program using F5 without debugging
- [x] 🏃 #433 Generate field tags in structs
- [x] #829 Load envFile in .vscode/launch.json
- [x] #558 keywords missing from completions list
- [x] #665 Rename issue due to unexpected output from diff tool
- [x] #846 Build fails to find vendor projects in case of symlinks 
- [x] #572 Overenthusiastic completion in package statement and single line import statement
- [x] 🏃 #872 Use the latest grammar from atom for Go
- [x] #873 Use default GOPATH/GOROOT 
- [x] #241 Support links in test output

Deferred:

- [ ] #828 Explore ways to sync the right version of the go-langserver
- [ ] Investigate #464 Syntax highlighting for html templates

**Comment by ramya-rao-a** [comment]
The update 0.6.56 has been released
