### ISSUE TITLE
Iteration Plan for April 2017 

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#890]
**Update**: Following April theme for VS Code, this plan has been updated to have more bug fixes than new features

Updated Plan:
- [x] #529 Auto-import imports package twice when file dirty, or doesn't suggest pkg if it was just deleted and file is still dirty
- [x] Live errors from other files get reported against the current file
- [x] #922 Go To Symbol in File.. doesn't consider unsaved file contents
- [x] #726 Show reference count as Codelens
- [x] Run tests via Codelens
- [x] #601 Toggle code coverage results
- [x] #942 Option to show only covered/uncovered code after getting code coverage results
- [x] #632 Option to set env vars to be used by the Go tools
- [x] #879 Debug tests via Codelens

Deferred Plan Items:
- [ ]  #647 Auto-import shows incorrect package name when package name is not same as the folder name
- [ ] #168 Suggestion for creating methods on types
- [ ] #259 Generate stubs implementing interface using impl
- [ ] #330 Browse package (either via F12 or via a new command)
- [ ] #588 [Investigation] Have another go at the extract method feature, this time using the free variables from `guru`

**Comment by ramya-rao-a** [comment]
The April update (0.6.60) is out!
Thanks everyone!
