### ISSUE TITLE
Iteration Plan for May - June 2017

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#959]
Update:

At the end of the May milestone we released 0.6.62 which had a bunch of bug fixes and the below 2 planned items

- [x] #259 Generate stubs implementing interface using imply
- [x] #962 References codelens support for methods

The other 2 are now moved to June

- [x]  #647 Auto-import shows incorrect package name when package name is not same as the folder name
- [ ] #168 Suggestion for creating methods on types

**Comment by sweetim** [comment]
Please enable explorer decorations for SCAM status! ;)

**Comment by qaisjp** [comment]
Glad to hear #168 has not been forgotten! Tried VS Code for the first time today and this is the only thing I've noticed missing from GoSublime so far!

**Comment by ramya-rao-a** [comment]
Sorry folks, May has been a busy month for me and I couldn't get to this. Will try to get an update out early June

**Comment by qaisjp** [comment]
What's the plan for #168?

**Comment by ramya-rao-a** [comment]
@qaisjp 
Completions get triggered for every new word that gets typed. 
We will have to parse the Go file every time the completions get triggered and find the types to offer the method constructor in the completion list.

I have a working model for it, but I am not yet happy with the "parse file for every completion model"
Because to do that I have to spawn a new process and call a Go tool.

The right way to do go about this would be using a language service (we don't have one yet that supports the auto complete feature). That way there is a service that knows the state and AST of the current file at any given time and can provide the necessary suggestion.

I'll try and get #168 in with the current working solution I have for the next update with a setting to turn it off. I am not sure what the perf implications would be when trying to spawn a new process for every word. Shouldn't be too bad, we already do that for every hover to get the hover info. Let's see.

**Comment by qaisjp** [comment]
Okay, that sounds fair enough. I've subscribed to #168 now, so please keep us updated there if you can, and when you have the chance!

Thanks for the quick reply :)
